airflow:
  connections:
  - conn_extra:
      example_extra_field: example-value
    conn_host: null
    conn_id: null
    conn_login: null
    conn_password: null
    conn_port: null
    conn_schema: null
    conn_type: null
  pools:
  - pool_description: null
    pool_name: null
    pool_slot: null
  variables:
  - variable_name: null
    variable_value: null
airflow_version: 2.8.4
python_version: 3.8.18
